
CREATE TABLE IF NOT EXISTS CompanyWebinar();
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS pageId text;
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS joinUri text;
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS webinarUrlAmericas text;
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS webinarUrlApac text;
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS webinarUrlEmea text;
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS icalUrl text;
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE CompanyWebinar ADD COLUMN IF NOT EXISTS displayPage text;

CREATE TABLE IF NOT EXISTS SiteUser();
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userId text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userEmail text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFirstName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userLastName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFullName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS seeArchived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS awesomeEffect boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayPage text;
