DROP TABLE WeatherObserved CASCADE;
DROP TABLE SiteUser CASCADE;
DROP TABLE CompanyEvent CASCADE;
DROP TABLE CompanyWebsite CASCADE;
DROP TABLE CompanyCourse CASCADE;
DROP TABLE CompanyResearch CASCADE;
