apiVersion: v1
kind: Service
metadata:
  namespace: computateorg
  name: computateorg
  labels:
    app.kubernetes.io/instance: computateorg
    app.kubernetes.io/name: computateorg
spec:
  ports:
  - name: http
    port: 10230
    protocol: TCP
    targetPort: 10230
  - name: cluster
    port: 10231
    protocol: TCP
    targetPort: 10231
  selector:
    app: computateorg
    app.kubernetes.io/instance: computateorg
    app.kubernetes.io/name: computateorg
    deployment: computateorg
  type: ClusterIP
